### ISSUE TITLE
Fog of Ominous Woods at Biomes O' Plenty is not valid

### ISSUE THREAD

**Issue by Piccot1214** [OreCruncher/DynamicSurroundings#120]
*Mod Version:*
DynamicSurroundings-1.11.2-3.4.5.6
*Forge Version:*
forge-1.11.2-13.20.0.2366-universal

*Description:*
I use BiomesOPlenty-1.11.2-6.2.0.2267-universal. Ominous Woods' fog doesn't function.

**Comment by OreCruncher** [comment]
Sometimes DS fog handling interferes with BoP handling and vice versa.  You can turn off DS biome fog handling.

**Comment by OreCruncher** [comment]
@Piccot1214 Do you have OptiFine installed?  If so take a look at [#62].

**Comment by Piccot1214** [comment]
Mod Version:
DynamicSurroundings-1.11.2-3.4.6.0
Forge Version:
forge-1.11.2-13.20.1.2414-universal

Yes, I use OptiFine and read #62, then turned off all fog option of DS. but still no function.

**Comment by OreCruncher** [comment]
@Piccot1214 Please turn on Dynamic Surroundings debug logging then restart your client.  When experiencing the issue press F3 to bring up the debug display.  On the left side of the screen about half way down you should see a line that looks like "FOG: IGNORED".

**Comment by Piccot1214** [comment]
I couldn't find the line that looks like "FOG: IGNORED".
I found only line that "AreFogScanner{color=[r:127,g:143,b:255], planeDistanceScale=0.75}"

**Comment by Piccot1214** [comment]
https://pastebin.com/4hiQgLzb
here plz

**Comment by OreCruncher** [comment]
Based on your config it should have "FOG: IGNORED".  I was able to repro the issue with the Ominous Woods, and when I disabled fog processing BoP was able to function.

**Comment by Technowix** [comment]
Same problem, even with every fog-related options disabled in the config, in wasteland :/

**Comment by OreCruncher** [comment]
I have changes going into the v3.4.9.1 release related to fog processing and BoP.  Should work much better.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.1 with fog compat changes with BoP.

**Comment by ate0ate** [comment]
This issue seems to have popped up again in 1.12.2 in the Ominous Woods. I do not know how many version this issue goes back as I have just encountered an Ominous Woods for the first time in an inordinately long while. I have not tried to disable dsurround fog handling, but using the default settings for all mods involved definitely results in complete white out (more accurately purple-ish) in the Ominous Woods. Its like the fog is ramped up to maximum. Wasteland and all other biomes seem perfect. I did not want to open a new issue as after reading through this thread I was unsure if the issue was fixed entirely or if the agreed upon solution was simply to disable fog handling for dsurround. I apologize in advance if this is already known or a waste of your time. I combed through the issues, both open and closed, and this one seemed to be a match. Thanks for the incredible mod and your time.
Possibly relevant info...
Forge 14.23.2.2634
Dynamic Surroundings 3.4.9.9
Biomes O Plenty 7.0.1.2334
Optifine D1

**Comment by OreCruncher** [comment]
It should be working with BoP.  Tested it with Ominous Woods myself.  Can you disable OptiFine to see if it goes away?  Sometimes all 3 together create an issue.

**Comment by ate0ate** [comment]
Removing Optifine definitely fixes the fog issue it would seem. It's strange that the mods all seem to work just fine until all three are put together. I do also usually have the fancy fog option turned on in optifine. I completely forgot about that. I can try messing around with more optifine settings in the mean time. Thank you for looking into things.

**Comment by OreCruncher** [comment]
See #298.  I do have a bug in DS related to BoP fog processing.  I am making a fix.  Once that is available it should work.

**Comment by ate0ate** [comment]
Very nice. Thank you! This coming update requires one of the newer forge versions due to the recent sound patch, correct? Anything at or after forge 14.23.2.2635?

**Comment by OreCruncher** [comment]
No need to update Forge.  DS will detect the version of Forge that is installed and selectively apply the patch as needed.

**Comment by ate0ate** [comment]
Understood. Thanks again. I will try it out as soon as possible.
