### ISSUE TITLE
Question about sound system crashes

### ISSUE THREAD

**Issue by xAlicatt** [OreCruncher/DynamicSurroundings#180]
From what I understand based on my research, Minecraft has limitations that cause the sound system to crash fairly often when mods like DS are used. For me it happens way more often than I would ideally like to see it happen and it causes a lag spike every time it crashes and restarts. Do you have any suggestions on how we can still use your mod without having the sound system crash all the time? Or is that just something that has to be dealt with if we want to use DS?

**Comment by OreCruncher** [comment]
Unfortunately the bug is down in PaulsCode, the sound library that Minecraft uses.  The crash occurs more frequently with any mod that makes heavy use of streaming sounds, such as Dynamic Surroundings, Ambient Sounds and the like.  CreativeMD has come up with a work around that I think is being integrated into Forge, but I am not 100% entirely sure.  Regardless, when I get back to things I will be looking at his work to see what I can include directly within Dynamic Surroundings so that the crash will not trigger.

**Comment by xAlicatt** [comment]
Will be eagerly following this, as I deeply enjoy the immersive quality of the various portions of your mod and similar mods. Until then, I have reluctantly made the decision to remove DS from my personal modpack. I do still use it in vanilla applications though, since it seems to happen less frequently there.

**Comment by darthvader45** [comment]
I am also looking forward to this, as I have been dealing with nasty lag spikes.  Hopefully this can be mashed into Forge 1.11.2, if not I'll gladly update to 1.12.2 once Ice and Fire finishes polishing their port.  Will hopefully allow for my blocks to transfer seamlessly, since I am only using vanilla blocks for now.

**Comment by xAlicatt** [comment]
@darthvader45 afaik, the Forge team never backports new features, so I would guess that if this change is made, it will only be available in whatever newest version they are working on as a release candidate is and forward from there. Which I think (right now) that would be 1.11, but won't be for much longer.

**Comment by darthvader45** [comment]
Alrighty, more reason for me to move to 1.12, I'm finishing up prep to move to it anyways.

**Comment by OreCruncher** [comment]
I plan on patching in some changes for DS to handle in the 1.10.x/1.11.x builds.  Hope to be getting to it in about a week.

**Comment by xAlicatt** [comment]
@OreCruncher Just following up here a few weeks later, do you know if the workaround has been rolled into Forge yet? My world is so, so quiet and it makes me sad. :P

**Comment by darthvader45** [comment]
Awesome, Ore.  Cannot wait to see what this means.  If it means less lag, I'm all for it.

**Comment by xAlicatt** [comment]
So I just wanted to pass this along. I installed DS on my 1.12 pack that has over 240 mods and I'm NOT getting the lag spikes anymore related to sound system. I don't want to get to excited about it, but it seems to be fixed. Sound hasn't crashed once and I've even been moving around and generating chunks and doing other CPU intensive things.

**Comment by darthvader45** [comment]
Sounds awesome.  I'm still waiting on the big update for Ice&Fire so I can finally move on to 1.12.2, and put my 1.11.2 days behind me.

**Comment by OreCruncher** [comment]
Following up.  Working on a set of changes to eliminate the sound engine restart stuff.  If it works out well I should have a BETA posted soon.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
