### ISSUE TITLE
Crash with IC2

### ISSUE THREAD

**Issue by bepis** [OreCruncher/DynamicSurroundings#181]
*Mod Version:*  1.10.2-3.4.7.2

*Forge Version:* 12.18.3.2477

*Link to crash log (if applicable):* https://pastebin.com/g3yFfPcx

*Description:* Will eventually get a notification that the sound system has crashed; later the game will crash to desktop.

**Comment by royalcw** [comment]
For my client, using the treetap from IC2 on a rubber tree will crash the game every single time unless I disable Dynamic Surroundings.  This is a shame because I love including this mod in all my packs.  This has been an issue in minecraft 1.10 and 1.12.2 packs that I've added Dynamic Surroundings to.

**Comment by Renadarain** [comment]
I get the same crash every time when using a tree tap - is there a fix for this?  

Thanks

**Comment by OreCruncher** [comment]
@Renadarain I am making changes to sound engine restart that should address the problem.  I have one of my worker bees (my son) testing the changes with IC2.  If things go well I should have the fix posted within a week.

**Comment by Renadarain** [comment]
@OreCruncher  thanks, and I'm sure that's why we have kids isn't it? lol

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
