### ISSUE TITLE
GL Error when Albedo enabled.

### ISSUE THREAD

**Issue by grugsy** [OreCruncher/DynamicSurroundings#194]
*Mod Version:*
3.4.7.2

*Forge Version:*
.2566

*Link to crash log (if applicable):*

*Description:*
getting a GL error 1281 when albedo is enabled in your configs. all entity/particle are white. (chests, mobs, player, footsteps)

**Comment by OreCruncher** [comment]
While running the game turn off albedo (using the albedo config), run the game a little bit, then turn it back on.  It corrects for me when I do this.

**Comment by OreCruncher** [comment]
@grugsy Which Minecraft version are you running?

**Comment by Boymann** [comment]
Just an observation and a further report on this bug, this was not as apparent in version 3.4.8.0 (footsteps mostly and monsters/other entities during rain) in 3.4.8.1 now it's back with white on most entities like chetsts/paintings all the time. Also, it makes some blocks flicker in the distance and causes the leaves to render in fast instead of fancy. 

Hope this helps a bit.

Tested on Minecraft 1.12.2, Forge: 2568 and 2586 respectively

**Comment by OreCruncher** [comment]
Unfortunately nothing changed with rendering between the two versions within DS itself.  Did anything else in your pack change?

**Comment by Boymann** [comment]
The only change that happened is the new version of dsurround and Instantunify 1.1.1

**Comment by OreCruncher** [comment]
Posted v3.4.8.2 with fix.

**Comment by Boymann** [comment]
Thank you very much!

**Comment by OreCruncher** [comment]
There may be some other strange artifacts in rendering.  I have some further in the next update.

**Comment by Boymann** [comment]
I'll try to help as much as I can!
