### ISSUE TITLE
Crash server on start

### ISSUE THREAD

**Issue by Tototi1** [OreCruncher/DynamicSurroundings#206]
*Mod Version:*
DynamicSurroundings-1.10.2-3.4.8.1
*Forge Version:*
forge-1.10.2-12.18.3.2511-universal

*Link to crash log (if applicable):*
https://pastebin.com/PY0qa1K7
*Description:*
Crash server on start.

**Comment by OreCruncher** [comment]
Will be fixed in the next BETA.

**Comment by Tototi1** [comment]
Oh good !

**Comment by OreCruncher** [comment]
I'm going to leave it open until I post the new JAR in case someone else has the issue.

**Comment by WesCook** [comment]
Glad to see this has been addressed.  I'm looking forward to trying out the releases with the sound engine patched.

Hope you don't mind the question OreCrusher, but do you have an ETA on the next release?  I only ask because Dynamic Surroundings releases can be intermittent, and I'm not sure if I should wait on pushing a modpack update or not.

No biggie either way.  I appreciate the continued support you give this mod.

Cheers.

**Comment by OreCruncher** [comment]
I hope to have a v3.4.8.2 done tomorrow (Sunday).  It's still going to be a BETA, though it should be stable.  Not sure of an actual release as of yet.  Working on a feature change and it is causing me some distress. :)

**Comment by WesCook** [comment]
Beta is quite alright with me.  It's modded Minecraft after all - there's no such thing as completely stable.  :)

Thanks for the update!

**Comment by OreCruncher** [comment]
Posted v3.4.8.2 with fix.
