### ISSUE TITLE
Ghost footsteps D:

### ISSUE THREAD

**Issue by SimulatorSia** [OreCruncher/DynamicSurroundings#224]
*Mod Version:* 3.4.9.0

*Forge Version:* 14.23.1.2599

You still make footstep sounds while crouching and sometimes I get a little lag spike then hear ghost footsteps at the place where my character was standing. It can last up to 15 seconds for me sometimes. o_o
The ghost footstep sounds are at a slow non sprinting pace and don't override my own. Meaning if I walk away, I hear the footsteps from the ghost fading while hearing my own simultaneously.

**Comment by OreCruncher** [comment]
What modpack are you using?

**Comment by SimulatorSia** [comment]
Not talking about footstep prints, talking about footstep sounds. Like normal pace creepy footstep sounds.

mods:
aether_legacy
AppleCore
AppleSkin
appliedenergistics2
armorchroma
base
Baubles
BetterFps
Bloodmoon
Blur
Botania
capabilityadapter
CarryOn
ChunkAnimator
clarity
Clumps
comforts
compactmachines3
coroutil
CosmeticArmorReworked
CreativeCore
dabmod
DynamicSurroundings
ElevatorMod
elulib
ExtendedDays
extrautils2
fairylights
FoamFixUnofficial - Lawful
furniture
GeneralLaymansAestheticSpyingScreen
GravityGun
HungerInPeace
iChunUtil
IGCM
InfernalMobs
ironchest
ItemPhysic Full
jehc
jei
jepb
JustEnoughResources
modnametooltip
multihotbar
multihotbarcore
MultiMine
mysticalworld
NetherPortalFix
paintingselgui
Pam's+HarvestCraft
Pam's+Pig+Skin
rangedpumps
RealisticTorches
roots-2
roughMobs
roughTweaks
Shatter-Mod
ShoulderSurfing
SilentLib
SoundFilters
sparkshammers
SurvivalTweaks
theoneprobe
UncraftingTable
torchmaster
Waystones
YarrCuteMobModelsRemake
zombieawareness

Sorry I have so many >.<
It's probably impossible to narrow down such an issue with this many mods. Plus I've been playing for an hour and not come across the glitch again.

**Comment by OreCruncher** [comment]
Believe it or not in the original Presence Footstep code the only sounds it won't play while the player is sneaking is when sitting on a ladder or when it simulates brushes (walking through things like grass).  

The difference you are seeing between this version and the prior one is the method used to detect when a player is moving.  Prior it was using an entity property that indicates how far a mob has moved throughout its life and required updates from the server; the new version I calculate my own based on the information present in the client.  The new way makes it more timely and accurate which is causing the sounds to play and prints to show.

All this being said I do think I need to make a change.  On multiplayer servers I don't think I want to produce prints and sounds for other players.  Question I have is whether you would want to hear your own footsteps.

**Comment by rckymtnrfc** [comment]
I'm not hearing ghost footsteps but it does seem the player's footsteps are more frequent in your latest update.  Perhaps having to do with your change on player movement detection.  It sounds like I'm running, when I'm only walking.  I switched back to the prior version and it's back to a more normal walking speed for the footsteps.

**Comment by OreCruncher** [comment]
@rckymtnrfc They are playing more frequently because of the detection method.  As mentioned prior steps were being missed because of the tardiness of entity updates from the server.  On my system the sound play lines up with the character leg animation (look at using F5).  I want to make sure I distinguish vs. running because running results in a different sound profile being produced.

**Comment by rckymtnrfc** [comment]
Thanks.  I guess I'll have to get used to it.  I'm just so used to the old speed of the footstep sounds....it's throwing me off and I keep checking to make sure I'm not running.  =)

**Comment by OreCruncher** [comment]
Understand.  It's something I thought about when I put the changes in.  I ultimately decided on matching it to the animation.

**Comment by OreCruncher** [comment]
@SimulatorSia I think the ghost footprints are related to the lag.  During a client lag spike your player can still move visibly because of lerping but footprint processing is stalled.  Once the spike clears it rushes to catch up thus giving the impression of footprints showing where you were.

**Comment by OreCruncher** [comment]
I have a fix going in to not generate footstep/jump sounds, or to show footprints, for entities that are sneaking.  Will show up in v3.4.9.1.

As for the lag spike not much I can do for the moment.  Lag could be caused by a variety of different things.  I haven't noticed anything specific to DS where things have become worse.

**Comment by SimulatorSia** [comment]
thank you

**Comment by SimulatorSia** [comment]
I backported one version and now I don't experience footstep sounds while crouching or ghost footsteps sounds at all.

**Comment by OreCruncher** [comment]
As mentioned prior there was a bug I fixed where footsteps wouldn't produce because of how frequent the entity is updated client side.  I fixed this and as a result footsteps would now play.  As originally coded footsteps in Presence Footsteps sounds these sounds should have played.  Footprints are tied to the production of sounds - no sound, no print.  In the version of DS I am working on I had to put in code explicitly not to produce sound when sneaking.

The lag spike is what is interesting me.  In my testing I haven't experienced lag spikes.  I use a hefty pack to do testing and haven't experienced the issue.  I do give my Minecraft instance 8GB to work with - how much memory do you give yours?

**Comment by SimulatorSia** [comment]
I give it 4gb ram. I do have a mac which isn't meant for gaming so it could be that.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.1 for the sneaking thing.  Also added timers to the debug screen (F3) so that if DS is the issue it would show up there.

**Comment by SimulatorSia** [comment]
<3<3<3
