### ISSUE TITLE
[Compatibility] Just Enough Dimensions

### ISSUE THREAD

**Issue by Efimero** [OreCruncher/DynamicSurroundings#245]
*Mod Version:* 3.4.9.3

*Forge Version:* 2611

*Description:* your custom thunder and rain effects don't happen in custom (JED) dimensions when using separate dimension worldinfo; sky goes dark, but the effects don't trigger.
I reported the issue to JED since you have a hook to trigger the storms, but maybe you could check for the mod and if so look for the per-world worldinfo file?
hopefully then both mods can work together

**Comment by OreCruncher** [comment]
It depends on how they handle their dimensions.  If they do something different than Minecraft it probably won't work.  I will take a look at mod compat and see if there is anything possible to do.  Thanks!

**Comment by OreCruncher** [comment]
https://github.com/maruohon/justenoughdimensions/issues/21

**Comment by maruohon** [comment]
How does Dynamic Surroundings handle the weather stuff, ie. how does it decide where to render the effects? I tried to look through your code back when that issue was posted for JED, but couldn't quite find what I was looking for (and then forgot to comment back on that issue >_>). So does DS check for the `DimensionType`, or which `WorldProvider` is in use (does it need to extend the vanilla Surface provider maybe?), or something else?

**Comment by OreCruncher** [comment]
First, the hooks:
* DS uses the Forge hook for render weather.  [On world load DS executes some code to hook it.](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/DynSurround/client/weather/RenderWeather.java#L74)  If another mod has already made a hook it does not - it assumes a non-cosmetic mod needs the hook.
* The actual rendering for Overworld occurs [here](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/DynSurround/client/weather/StormRenderer.java#L112).  It is very similar to how Minecraft does rendering, but has enhancements for dust, different precipitation strengths, optimizations for performance, etc.
* For rain splash particles and sound DS uses ASM to intercept the call and [redirects to this method](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/DynSurround/client/weather/RenderWeather.java#L59).

From a default standpoint DS assumes that a [dimension does not have weather effects](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/java/org/blockartistry/DynSurround/registry/DimensionInfo.java#L53).  It relies on [configuration data](https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/resources/assets/dsurround/dsurround/data/mcp.json#L720) to determine if weather actually occurs within a dimension. 

The reason DS assumes no weather for a dimension is because most of the modded dimensions that it runs into are either space related (like Galacticraft), have some weird properties (RFTools and Mystcraft), or has their own needs for controlling weather (like Twilight Forest progression).  Personally I would like to see a properties on dimensions similar to that on Biomes where a mod author can indicate things like weather, space, air, etc.

**Comment by OreCruncher** [comment]
Yes, a pack author has the ability to configure DS behavior using external JSON config files, including turning on weather for a dimension.
