### ISSUE TITLE
Erebus support

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#261]
Would it be possible to add Erebus support?

Normally, I'd just commit this myself but I've been having some lagspikes possibly relating to Java's garbage collection that I'm trying to figure out how to solve.

**Comment by OreCruncher** [comment]
Check v3.4.9.5 I just posted.  Has the beginnings of Erebus support.  Actually has quite a bit of it.

**Comment by Sunconure11** [comment]
I had just updated to it. I'll see if I can tweak it when I can get these lag spikes in singleplayer dealt with.

**Comment by OreCruncher** [comment]
@Sunconure11 Looking at Erebus support right now.  Seems like blocks/footstep stuff works as is.  Big thing is there are no biome sounds.  Main reason is that the player is considered "inside" because Erebus is underground and has no sky.

I was wondering what your thoughts were on this.  There are several things I could potentially do:
- Put in code that will tell DS that the player is always outside for a dimension.  This will allow the biome sounds to play based on the biome traits.  Downside is that the biome sounds will play even when the player is in a tunnel.
- Have some sort of dimension sound track.  I do this for the Nether and The End.  Again this will play all the time.  I could reuse the night cricket sounds, but for this I would think it would need to be different.  This does not address the issue of blocks that need to be outside to have effects, like the frog croaks w/lily pads.

**Comment by OreCruncher** [comment]
Decided to do bullet 1.  This allows for much more variation as well as spot sounds and what not.

**Comment by OreCruncher** [comment]
Pushed v3.5.2.0 to CurseForge with Erebus related changes.
