### ISSUE TITLE
World Crashes upon loading

### ISSUE THREAD

**Issue by beanaboston** [OreCruncher/DynamicSurroundings#263]
*Mod Version:* 1.0.6.0 for 1.7.10

*Forge Version:* 10.13.4.1614

*Link to crash log (if applicable):* https://pastebin.com/KHhWi2Da

*Description:* Opened world, and it immediately crashed. I relaunched Minecraft and was able to enter world. Posted to /r/feedthebeastcrashes and someone said that it looks like it was Dynamic Surroundings, and that I should post it here.
In the case that it may be a conflict my mod list can be found here: https://www.modlister.com/user/beanaboston

**Comment by OreCruncher** [comment]
No, DS didn't do that.  It just gets fingered for it because the mod's name is in the call stack.  In the cases I have seen this is due to another mod reaching in from a thread other than the client thread (such as from the server thread) and trying to do something with sounds.  I recently put in some changes into the 1.10.x+ versions that guard against this bad behavior just so I *don't* get these reports. :)  I may backport those changes once I finish up with my current release train.

**Comment by beanaboston** [comment]
Ah, all right. That makes sense. Sorry for bothering you with this. Thanks for explaining it.

**Comment by OreCruncher** [comment]
No worries.  I would rather hear about problems than not, even if they aren't mine. :)

**Comment by OreCruncher** [comment]
Pushed v1.0.6.1 to CurseForge with several updates.  Let me know if it fixes things.
