### ISSUE TITLE
Config Question 

### ISSUE THREAD

**Issue by Adarcer** [OreCruncher/DynamicSurroundings#348]
how do i disable certain sound events ... for example i created a shortcut over water with lilypads but when i walk over them frog "croak" sounds play

**Comment by Adarcer** [comment]
1.12,2-3.4.9.13

**Comment by OreCruncher** [comment]
Using the Forge mod configuration system you can block any sound in the mod pack.  Access by clicking the "Mods" menu item, select "Dynamic Surroundings" from the list on the left, then click "Configure" in the lower left corner.  Scroll down the resulting dialog and click "Individual Sound Configuration".

I am assuming you want to block the frog croak sounds.  The two sounds you want to block are "dsurround:frog" and "dsurround:bullfrog".  Note that these sounds are not footstep related.  They are block sounds that will randomly play because the player is in range of the block.

**Comment by OreCruncher** [comment]
As indicated to prevent the frog sounds from playing block the above mentioned sounds.

**Comment by OreCruncher** [comment]
@Adarcer Were you able to block the sound?

**Comment by Adarcer** [comment]
yah I can block the sound. but i really just wanted to limit the amount or remove the lilypads from playing the sound so i just dug up my lilypads and stored them
