### ISSUE TITLE
[SUGGESTION] Reimplementing void fog, void particles

### ISSUE THREAD

**Issue by Aleszp** [OreCruncher/DynamicSurroundings#35]
Hi!
What would you say about reimplementing void fog and void particles that got removed in Bunny.... I mean Bountiful update? It would restore that bit of creepy uncertainty while mining deep.

**Comment by OreCruncher** [comment]
Based on what they said it was removed for performance reasons.  I have no specifics other than that.  I can take a look at it but no promises.

**Comment by Aleszp** [comment]
Personally I didn't notice much of performance gain after updating to 1.8 (actually 1.7 was faster for me 30-40 FPS on 1.7 even with mods and ~15FPS on 1.8 with just optifine on my older machine). Those two features (from my point of view) would fit DynamicSurroundings nicely (especially that all of features are highly customizable and somebody experiencing problems could just turn it off) and it (probably, my guess) may reuse some of code that handles sandstorms on deserts.

(Now I wonder why Mojang didn't just add an option to disable voidfog for people who have problems with it/don't like it).

**Comment by OreCruncher** [comment]
I think the performance aspect is more related to the number of particles being rendered.  The number of "depthsuspend" particle effect (those black motes that seem to hang in the fog) generated per tick could be pretty high when at the very bottom of the world.  I can see where some clients could struggle with it.  I have to be careful with some of that myself because I do make use of a lot of particle effects.

Looking at the code it would be easy to add back the "depthsuspend" particles.  The void fog, though, could be a pain.  Dealing with Fog in Minecraft is nasty.

**Comment by OreCruncher** [comment]
More on this topic.  The suspend particles were removed because air blocks were being ticked client side.  Needless to say there can be a lot of air blocks. :)  Not sure about adding back in the particles, but I can see about adding something related to fog.

**Comment by OreCruncher** [comment]
Next BETA v3.4.9.1 will have the void fog.  I don't think I will do the particles because of potential lag challenges.  That is a lot of air blocks ticking.

**Comment by Domaaaa** [comment]
Don't forget to add on/off toggle!

**Comment by OreCruncher** [comment]
Yep - thats in there. :)

**Comment by OreCruncher** [comment]
Pushed v3.4.9.1 with the enhancement.
