### ISSUE TITLE
[Suggestion/Enhancement] Extra Info Popup for Serene Seasons' Season Clock

### ISSUE THREAD

**Issue by TechnoMysterio** [OreCruncher/DynamicSurroundings#350]
For an enhancement, it may be good to have additional season information in a popup (like with compasses/ordinary clocks) for Serene Seasons' season clock.

Since the standard clock popup now has the current season listed, it makes the season clock somewhat redundant. However, implementing a unique popup for the season clock that shows other useful seasonal information (e.g. current temperature sub-season, current tropical sub-season, current year/month based on full seasonal cycles, progress in days/hours/etc through current year/season, time until next sub-season, maybe even more abstract stuff like what crops can be grown in the current season or weather forecasts) would make the season clock be far more useful, and would also make it useful for testing the Serene Seasons mod itself.

**Comment by OreCruncher** [comment]
Changing DS so that the season info portion of the HUD will only show when holding a season clock, or looking at a season clock when in an item frame.  The Minecraft clock will no longer show season info.

The extra detail related to season calendar, crop growing conditions, etc. is interesting.  I feel, though, that extra detail would be suited for a Serene Seasons add-on that can provide the data via The One Probe, JEI, and similar mods.

**Comment by TechnoMysterio** [comment]
I mainly thought the bonus info would be useful if the standard clock showed the season anyway, so it was less redundant, but it's less of a problem if the season clock is now the only thing that shows the season info.

**Comment by OreCruncher** [comment]
Yep.  In retrospect I should have taken this approach originally.  As you point out the prior implementation pretty much neutered the season clock.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.15 to CurseForge with a fix.
