### ISSUE TITLE
Dynamic Sounds is missing mods

### ISSUE THREAD

**Issue by Timtendo12** [OreCruncher/DynamicSurroundings#357]
*Mod Version:*
1.12.2
*Forge Version:*
1.12.2-Forge1.12.2-14.23.0.2552
*Link to crash log (if applicable):*
[http://www.mediafire.com/file/s4q2nfl514rxn9h/fml-client-latest.log/file](url)
*Description:*
So when i start Minecraft it says: 

> 2 mods are missing a mod they depending on 

The mods i have installed:

Optifine
DynamicSurroundings
FastLeafDecay
BetterFoliage
Streams
Worldedit

ples help (◕ᴥ◕) Doggo needs help! :)

**Comment by OreCruncher** [comment]
Can't access the log file.  DS does not depend on any other mod.

**Comment by OreCruncher** [comment]
@Timtendo12 Any update?

**Comment by MauveCloud** [comment]
I think Timtendo12 tried to use a bbcode-style link instead of GitHub-style, but if you copy and paste the visible url, you can access it that way.  However, that shouldn't even be necessary to see why this is happening.  Dynamic Surroundings requires at least build 2555 of Forge, and the OP has indicated build 2552 is in use.

**Comment by OreCruncher** [comment]
That would be it.  The error generate by Forge should have been clear about that particular dependency. :)

**Comment by OreCruncher** [comment]
@Timtendo12 Did updaing Forge address the problem?

**Comment by OreCruncher** [comment]
Closed due to inactivity.  If there are any further issues let me know.
