### ISSUE TITLE
Crash After Updating From 3.4.9.17 to 3.4.10.0

### ISSUE THREAD

**Issue by KenyMylankca** [OreCruncher/DynamicSurroundings#387]
*Forge Version:*
2772
*Link to crash log (if applicable):*
[crash-2018-11-02_22.20.29-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/2543859/crash-2018-11-02_22.20.29-client.txt)
*Description:*
First of all, i'm not %100 sure it's about Dynamic Surroundings, but this crash happens randomly while playing. And it started happening after updating DS. Sorry if it's not about DS, but i need help :(

**Comment by OreCruncher** [comment]
I can't say with 100% certainty what who the culprit is.  But in general these things are caused by the server side thread trying to play a sound.  What happens is that mod logic works with the client side classes which is a big no no.  Depending on how you feel you can do one of two things:
* In the Dynamic Surroundings configuration you can set "Enable synchronized for Sound Manager".  This will cause DS to modify some java code at startup to synchronize (or only let one call through) to the SoundManager at a time.  So if indeed the server thread is trying to talk with client code, and the client thread wants to do something, they won't step over each other.
* You can put DS in developer mode.  Add "-Ddsurround.devMode" (without the quotes) to your Java command line parameters.  What this will do is cause DS to audit what thread is doing what with the sound engine.  If it detects that a thread other than the client thread does something with the sound engine it will cause your client to crash, generating a callstack in the process.  This callstack will allow us to pin point the mod that is causing this issue.
Which of these options you pick is up to you.  The first gets you back to playing, the second helps find the root problem and we can notify the mod developer.  Of course, you can do the 2nd, and when we identify the problem you can do the 1st until a fix is made.

**Comment by KenyMylankca** [comment]
Thank you so much for your help! I will try those things and give you feedback if would needed by you.

**Comment by OreCruncher** [comment]
Yes, I would like feedback as to the results.  I have an interest in which mod is causing the difficulty.

**Comment by KenyMylankca** [comment]
Uhm, last night, i just did [this.](https://github.com/KenyMylankca/Harshen-Modpack/commit/41a5108bf9e4bfd4f90baa725ea0cec692b1ff2c) Then we played about 45 mins, and it didn't crash. I can help you understand which mod causes if you wish. BUT, my guessing is, it's Weather mod. You could take a look into that :p

**Comment by OreCruncher** [comment]
Cool.  If I were to guess I would say Ice and Fire.  Reason is, well, those two settings you turned on I put because of Ice and Fire. :)  I am going to close the defect, and if you run into any further problems let me know.
