### ISSUE TITLE
Crash that is preventing me from viewing compatibility issues with a set of unrelated mods

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#404]
https://pastebin.com/zfkUHwA6

**Comment by OreCruncher** [comment]
Yeah - this is a tough one to resolve.  The DS core mod ran, but DS itself isn't loaded because the startup is stillborn.  You figure Forge would stop further execution in the client, but for whatever reason it continues and wants to play music and other stuff. :\  For your particular circumstance you could remove DS and it's coremod, resolve the dependency issue, and put it back in.

This problem is something I am looking at for 3.5.  Not sure how I can resolve at the moment.

**Comment by OreCruncher** [comment]
Pushed a BETA of v3.5 to CurseForge.  Note that the new version has a library dependency on OreLib (another library mod I made).  Make sure you read the release notes prior to upgrade.
