### ISSUE TITLE
Crash (NoClassDefFoundError)

### ISSUE THREAD

**Issue by KingCactaur** [OreCruncher/DynamicSurroundings#416]
Mod Version: 3.4.10.4
Forge Version: 14.23.5.2776

https://pastebin.com/EN1QUzze

Description:
Crash on startup

**Comment by OreCruncher** [comment]
There is a mod dependency failure that is being triggered by something.  When that happens DS is left hanging in a weird init state and you can get this crash.  Temporarily remove DS to see what Forge is complaining about.  BTW, can you link your client log?  It may state exactly what is needed.

**Comment by KingCactaur** [comment]
I had previously removed DS because of the crash, but after adding it back it seems that I can't replicate it? I'm not sure when I'll be able to sit down and continue to test but if I get this crash again I'll add to this thread.

**Comment by OreCruncher** [comment]
What version of DS were you running prior to putting in 3.4.10.4?

**Comment by KingCactaur** [comment]
Nothing; My first install was in 3.4.10.4 and the instance I just ran was also in 3.4.10.4

**Comment by OreCruncher** [comment]
Yeah - this isn't making too much sense.  What modpack are you using?

**Comment by KingCactaur** [comment]
It's my own private pack

**Comment by OreCruncher** [comment]
Can you post your client log?  It may have further information in terms of the chain of events leading up to this crash.

**Comment by KingCactaur** [comment]
Forgive me if I'm mistaken, but since I managed so successfully ran the game again, isn't the log overwritten?

**Comment by KingCactaur** [comment]
[2018-12-02-1.log.gz](https://github.com/OreCruncher/DynamicSurroundings/files/2644689/2018-12-02-1.log.gz)

Let me know if this is the wrong one

**Comment by OreCruncher** [comment]
It's the right one.  This is what I found:
```
[15:21:58] [main/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod dse (Deep Sea Expansion) requires [nhc@[4.0.3,)]
```
What this means is that Deep Sea Expansion had a dependency on another mod (nhc) and it could not find it.  When this occurs the startup process of the client is disrupted and leaves Dynamic Surroundings in a weird state.

The core mod of Dynamic Surroundings makes changes to Minecraft's SoundManager to clean up some bugs and stuff.  The coremod ran doing what it needed to do.  However, since the main Dynamic Surroundings mod has not loaded the linkage created by the core mod will fail and crash with the NPE.

I am backporting some changes from my active development branch to help address this issue.  Specifically, don't crash and let Forge display the necessary dialogs indicating the mod dependency failure.

**Comment by KingCactaur** [comment]
Alright thanks for the help

**Comment by OreCruncher** [comment]
Pushed v3.4.10.5 to CurseForge with fix.
