### ISSUE TITLE
[Suggestion] Option for vanilla rain texture, and pixelated water ripple style

### ISSUE THREAD

**Issue by Forstride** [OreCruncher/DynamicSurroundings#418]
I really love the enhanced weather, and it's not that the rain texture in the mod looks bad by any means, but I personally like the color of the vanilla one more, so an option to change that would be nice.  It might be good to add another style that matches the new default water color in 1.13 to prepare for that as well, or for anyone who's using the preview of the new textures on 1.12.2.

Additionally, I feel like the smooth scaling water ripples that appear when it's raining clash with Minecraft's pixelated art style, and a proper pixel animation style would be great.

**Comment by OreCruncher** [comment]
Have you checked out the other ripple effects?

**Comment by Forstride** [comment]
Yeah I've tried the square one.  I just meant that instead of scaling the texture through code, it would be nice to have an actual frame-by-frame animation that remains at a single pixel ratio.  I could even make it for you if you wanted to implement this.

**Comment by OreCruncher** [comment]
If you got the gumption to do that I will see about wiring it in.  May need some pointers if it is an animated texture - haven't done one of those before.

**Comment by Forstride** [comment]
Right.  It would just display the animation at a static size, and then fade it at the end (Although I guess that could technically be done in the animation too, but it's probably better to just handle with code).

**Comment by OreCruncher** [comment]
BTW, you wrote "something like this should work", and several blank lines.  Am I supposed to see something there?

**Comment by Forstride** [comment]
Yeah I had uploaded an image to GitHub.  Guess it's not working properly.  Here's an imgur mirror: https://i.imgur.com/1c0p7SY.png

**Comment by OreCruncher** [comment]
Cool.  I will run with this and do some prototyping to see what I can come up with.  BTW, just looked at 1.13 rain.  I think the falling texture is the standard vanilla texture.  The splashes, though, are colored a bit different.  There are several colors of blue in them.

**Comment by OreCruncher** [comment]
@Forstride Opinion? https://ibb.co/Y3MbNb1

**Comment by Forstride** [comment]
I might need to make it a bit bigger, and it's hard to judge without seeing the actual animation work properly, but it looks good!

As for the rain, I feel like it should just be a standard color everywhere.  Honestly, I doubt that many people care about the rain color, so just having an option for your texture and vanilla's should satisfy most people.

**Comment by OreCruncher** [comment]
I will leave the pixelated rain ripple as is until you can get a feel for it.  A static picture really doesn't do it justice.  It does have the Minecraft animated texture feel to it.  As for bigger I can scale.  As for needing a little more resolution it could be a good idea.  IIRC each frame is 8x8 rather than 16x16.

**Comment by Forstride** [comment]
I made a larger version if you wanna try it out: https://i.imgur.com/8msJFAj.png

**Comment by OreCruncher** [comment]
Looks better I think.  I will update the textures for the drop.

**Comment by OreCruncher** [comment]
I am also updating the textures for rain.  Essentially I am using the original MC texture as a  base, and then selectively removing elements to produce textures for various intensities.  I am also adding 2 new intensities to smooth out transitions.  Even with these changes there is a coloration difference between the strongest intensity (the MC texture) and my other derived textures.  Not sure why as of yet.  Nothing is apparent in code, and nothing is apparent in the texture.  Go figure.

(I haven't ruled out fog and sky color calculations.  Those are based on my internal intensities rather than the world intensity.  Not sure how this could affect rain rendering but...)

**Comment by OreCruncher** [comment]
Figure out the rain texture problem.  When saving the texture the alpha threshold was off so the rain textures appeared more white.  The next drop will have updated textures.

**Comment by OreCruncher** [comment]
Pushed v3.5.1.0 to CurseForge.  Has the pixelated ripple and updated rain textures.  You will have to set the ripple type to 3.  I may set as a default depending on the final result.

**Comment by OreCruncher** [comment]
@Forstride Have you had a chance to check out the new rain ripple?

**Comment by Forstride** [comment]
Not yet.  Smash Ultimate just came out yesterday so I've just been playing that constantly lol

**Comment by OreCruncher** [comment]
lol - priorities.  Gotta ask my son if he saw it.

**Comment by Forstride** [comment]
Just tried it and the ripples look great!  The vanilla-style rain is looking good too.  Thanks for adding this!
