### ISSUE TITLE
Preset submod not populating cfg in 3.4.10.x

### ISSUE THREAD

**Issue by Gamertech** [OreCruncher/DynamicSurroundings#419]
*Mod Version:*
3.4.10.x
*Forge Version:*
14.23.5.2771

*Link to crash log (if applicable):*
N/A
*Description:*
Config option to disable online version check is no longer functioning from 3.4.10.2

Players get a chat message with update info on world load they don't need to see (and may be pack breaking if they did update it).

Minor bug, but if that could be fixed, it'd be excellent thank you.

**Comment by OreCruncher** [comment]
For the most part a newer client would work with an older server and vice versa.  Not much has changed in the communication between client/server.  So there isn't an immediate danger for your players.  I will check into the version thing - I haven't touched that code in a while.

**Comment by Gamertech** [comment]
https://pastebin.com/1XYsc7wJ

Yea, as I said just a minor issue, but if they did decide to update, the update button on the Twitch app would install the new 3.5.x beta which has forge version conflicts with some other mods in my pack, causing a crash on load.

Mainly I want to keep the chat clean on world load and DS is the only mod left posting update info in it.

Cheers for looking into it.

**Comment by OreCruncher** [comment]
Oh!  Talking about the Twitch update notification.  I have no control over that. :\  As soon as a push a newer non-alpha build Twitch will indicate a new version is available.  Now, if this pack is a published pack and the players are downloading the pack instead of individual mods then Twitch shouldn't be indicating that mod updates are available.  Updates should only be available when the pack updates version.  But, if they are downloading individual mods and assembling their own local pack to play they will get Twitch "updates available" options.

In terms of runtime, Forge does all the version checking using it's framework.  The DS setting controls whether a chat message related to the result of the version check is output to the user on log in.  Outside of DS Forge will badge buttons and mod entries with green circle like thing to indicate that a mod update is available.  IIRC you can turn this version checking off in Forge.  If you haven't you may want to do so.  When turned off DS should not report anything in chat regardless.

**Comment by Gamertech** [comment]
No sorry, I mean in the actual game world, I get a notification in the MC chat from Dynamic Surroundings that links to the Curseforge files page for the mod.

Regarding the Twitch launcher I'm saying that if people react to the DS update notification in game and manually update via the Twitch launcher to get rid of it, the current latest DS update will crash the pack.

This line right here:
![dynamicsurroundings](https://user-images.githubusercontent.com/16890798/49597681-0d372900-f9d1-11e8-96d1-9cf5231f9b30.jpg)

**Comment by OreCruncher** [comment]
OK - that's presets.  Looking in the wrong place.  Lemme check that.

**Comment by Gamertech** [comment]
Checked there, the presets.cfg has no options inside it at all, just:

```
# Configuration file

~CONFIG_VERSION: 3.4.10.4
```

**Comment by OreCruncher** [comment]
OK.  Think I found the issue.  There was a line missing in the config load process thus the default settings never made it to disk.  Wee!

**Comment by OreCruncher** [comment]
Pushed v3.4.10.5 to CurseForge with fix.

**Comment by Gamertech** [comment]
The config populates correctly now and the version option is there. Thanks for the quick fix.
