### ISSUE TITLE
[1.7.10] Sound bug

### ISSUE THREAD

**Issue by Managarmr719** [OreCruncher/DynamicSurroundings#45]
*Mod Version:* 1.0.5.9

*Forge Version:* 10.13.4.1614

*Description:* 
Weird sound bug, it's specially bad when moving around. Going back to 1.0.5.7 fixes it.
Recordings:
Broken:https://drive.google.com/file/d/0ByBK1E1PKZ5QbHRUYVhURTNPazA/view?usp=sharing
1.0.5.7:https://drive.google.com/file/d/0ByBK1E1PKZ5QRlVEWjNhR0lEaU0/view?usp=sharing

**Comment by OreCruncher** [comment]
Does it sound like stuttering?

**Comment by Managarmr719** [comment]
yes, when I move around the sound starts stuttering, crackling and popping.

**Comment by OreCruncher** [comment]
Still haven't found the source of the issue.  Reviewed the code changes between the versions and the majority are related to updating the OGG sound files and some bug fixes for the footsteps.  Nothing in the area of code related to biome and spot sounds. :\

**Comment by Managarmr719** [comment]
I tested again in a new a world with a new installation and it's not as bad as before, the crackling and the popping are a bit better, the stuttering is still present and while it's not very noticeable during normal gameplay, the faster I go (flying for example) the faster and worse the stutter is. I don't really know but I don't think that it's just the volume that's changing and causing the stutter, otherwise why would be the sound crackling and popping :\.

**Comment by OreCruncher** [comment]
Exactly.  Flying makes it worse because movement speed is faster.  When walking on the ground during "normal" gameplay it isn't too noticable.  Find a large biome, such as a Forest, and go to the center and then fly around.  It should be even less.  Note that there could be some stutter - the sounds are attached to the player position and they update 20 times a second (once per tick).  Some people can notice it, most not.

Another way you can observe it is to enable Dynamic Surroundings debug, and hit F3.  The currently playing background sounds will be listed along with their current volumes.  You will notice that the stutter corresponds with the changing of a sounds volumes.

**Comment by Managarmr719** [comment]
You're probably right but the occasional crackling and popping is still really annoying. Furthermore I would guess the newer versions for 1.8+ work basically the same way but I tried with the newest version for 1.11.2 and didn't have this problem, I still hear the stuttering but it seems much smoother and the crackling completely disappears.

**Comment by OreCruncher** [comment]
Yep - the 1.10.2/1.11.x versions are much better in terms of smoothing out the volume at boundaries.  The 1.7.10 version changes the volume abruptly as the player moves whereas the 1.10.2/1.11.x fades in/out to the target volume.  I backported some of the changes from 1.10.2/1.11.x and the jerky volume transition disappeared.

**Comment by Managarmr719** [comment]
As a side note, shouldn't the config option for Fancy Cloud Handling be removed as the functionality itself was removed in version 1.0.5.7?

**Comment by OreCruncher** [comment]
Yes.  It's on my cleanup list.  The actual logic internally has been removed.

**Comment by OreCruncher** [comment]
Posted a 1.7.10-1.0.5.10 version that should address this problem.
