### ISSUE TITLE
[1.16.4] [Question] How to disable The End Dimension music/sound?

### ISSUE THREAD

**Issue by mr-poyo** [OreCruncher/DynamicSurroundings#658]
**Mod Version:**
DynamicSurroundings-1.16.4-4.0.3.5.jar

**Forge Version:**
36.0.1

**Description:**
I was wondering how to disable the end.ogg that plays in the end dimension? It is nice and creepy, but I am aiming for a more mystical feel with my mod choices and was wondering if i could disable this particular sound file. Thank you!

**Comment by OreCruncher** [comment]
Easiest way is to block the sound.  While in game hit CTRL+i.  Search for "environs:theend" and set it to be blocked.  If you do this while in the end you will need to leave and re-enter.  Reason is block will only happen at the time the sound is played, and will not affect sounds that are already playing.

There will be other ways to modify the dimension settings.  I have not published the methods as of yet because they are in process of being tweaked.

**Comment by mr-poyo** [comment]
Thanks. Worked like a charm.
