### ISSUE TITLE
[1.16.5] The latest version is incompatible with realms.

### ISSUE THREAD

**Issue by HereToSaySomething** [OreCruncher/DynamicSurroundings#685]
Mod Version: DynamicSurroundings-1.16.4-4.0.3.12.jar
Forge Version: 1.16.5-forge-36.0.43

Description:
The game did not crash. When I tried the latest version of the mod on Realms, it froze me in place and set me in survival mode, no matter what mode I was on previously. I could only interact with the blocks around me. My movement wasn't working.

I tested switching back to an earlier version of the mod(DynamicSurroundings-1.16.4-4.0.3.11.jar) and everything was fine again. I was back to creative mode and I could move.
This was also the case when there was no Dynamic Surroundings Mod.

DynamicSurroundings-1.16.4-4.0.3.12.jar worked fine in a single-player world, just not on realms. 

I have 15 other mods (including OptiFine) that I have downloaded. I updated Forge a couple of days ago.
I'm new to mods so I'm just starting to figure things out.

**Comment by OreCruncher** [comment]
Can you link the debug.log file from a session that gives you the problem?  You can find it in the logs folder where the Minecraft instance is located.

**Comment by FoxMcloud5655** [comment]
I am also having this same issue, though it happened in a multiplayer LAN server instead (not dedicated; didn't test).  On this same note, DynamicSurroundings was also crashing any clients that connected to a server with SimplyJetpacks version 2.6.7.1 installed, for whatever reason.  Downgrading either of the mods fixes that problem, though I think the problem with the other mod is due to a non-existent null pointer check.

With that being said, the file that contains my log is buried somewhere in my logs file and I'm not sure which one it is; I'd rather not give you false information.  I'll immediately report back if I encounter the issue again.

**Comment by OreCruncher** [comment]
@FoxMcloud5655 I would like to see the log with the crash even it is the other mod.  Maybe there is something I can tighten up in code on my side.  Also, as it relates to the LAN question - is it hosting, or when trying to connect to another?

**Comment by OreCruncher** [comment]
Try out this JAR: https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.4.1

**Comment by FoxMcloud5655** [comment]
It's when connecting to another instance of the Minecraft client via LAN.  Most everything loads up fine and you're able to see the hotbar and the sky, but before any chunks actually load in, the game crashes.

I see you added some extra debug stuff to the latest release, so I'll try it out and report back.

**Comment by FoxMcloud5655** [comment]
I apologize; I didn't see that you had a separate repository for 1.16.4+, otherwise I would have created another issue there.

I've tested both versions multiple times and the new version fixes the issue on my end.  Attached are logs for both runs so you can compare the two if you'd like.  One is labeled as the crash and the other is using the version you just linked.

[Log Files](https://github.com/OreCruncher/DynamicSurroundings/files/6063021/logs.zip)

**Comment by OreCruncher** [comment]
No worries on the repo.  I will accept all DS related issues on this tracker.  It's easier than switching back/forth.  As for the crash it looks like it is in Simply Jetpacks.  Not sure as to the actual why.

**Comment by FoxMcloud5655** [comment]
Yeah, that's what stumped me at first.  I had originally made an issue on their GitHub repo, but through working down all 200 of my own mods, I eventually came to Dynamic Surroundings and Simply Jetpacks having an incompatibility for whatever reason.

**Comment by OreCruncher** [comment]
It looks like timing.  Their logic assumes that a property on the player is initialized to a non-null value.  It is possible it is null and has not been set because their handler is firing during the client tick.  I have seen similar things when working on DS.

EDIT: And it looks like that change [was made 16 days ago](https://github.com/Tomson124/SimplyJetpacks2/blob/914326eba3fe41fffce8dfeedae8f81bb8fb7437/src/main/java/stormedpanda/simplyjetpacks/handlers/KeybindHandler.java#L78). :)

**Comment by spicypepperoni** [comment]
Also having this problem. Logging into a realms server gives me a "Incomplete set of tags" problem. Uninstalling the mod works. I tried using the latest jar, .12 and an earlier version, .11. Nothing changes and still have the problem.

**Comment by spicypepperoni** [comment]
Also I think something to do with this tags problem might have also effected my .minecraft folder in some way. Logging onto Hypixel greeted me with a ban notice of 178 days. I have no reason to be banned. And this only occurred with the mod installed

**Comment by OreCruncher** [comment]
@spicypepperoni Did you install the JAR linked above?

**Comment by OreCruncher** [comment]
@HereToSaySomething @spicypepperoni Have you tried the linked jar to see if it resolves your Realms issues?

**Comment by CelluloidRacer2** [comment]
I'm having the same issue on a custom modpack server. Seems this mod is the culprit as the issue doesn't come up without the mod enabled.

I tried the version linked and it didn't fix the issue. 

It looks like you have the right idea here, I noticed that you can still break things, however the speed is very slow even when on the ground (flying breaking speed). You also get kicked for flying if the block under you is clear.

Edit: 
The versions I've tried: 
 - 1.16.4-4.0.3.12
 - 1.16.4-4.0.4.1

**Comment by OreCruncher** [comment]
@CelluloidRacer2 What prior version did you use that worked?

**Comment by CelluloidRacer2** [comment]
@OreCruncher I haven't had any versions work

**Comment by OreCruncher** [comment]
Then it is something entirely different.  Not sure about the flying stuff - DS has nothing to do with that.  It also does not affect movement.  Can you open a new issue, and link your debug.log to the incident?

**Comment by CelluloidRacer2** [comment]
> The game did not crash. When I tried the latest version of the mod on Realms, it froze me in place and set me in survival mode, no matter what mode I was on previously. I could only interact with the blocks around me. My movement wasn't working.

@OreCruncher if you re-read the original post, this is the same issue, just outside realms.

Whenever you join a server, it holds the player in place, and you can only interact with the blocks immediately around you. If the DynamicSurroundings mod is NOT present, it doesn't occur. If flight is disabled on the server and there's a block missing under the player, you get kicked after a second because "flying is not enabled".

This issue is not related to SimplyJetpacks, it's not installed on the pack I'm using. It's related to a bug in DS.

**Comment by OreCruncher** [comment]
As mentioned do you have a debug.log available?

**Comment by Cokenpizza** [comment]
Hey there!  Not either of the other OPs, but I also found this issue when converting my forge server to a mohist server.  Never had the issue on forge only, but mohist caused me to be frozen in place and unable to move.  Also realized the perspective was locked because I casted a couple spells from Ars Nouveau that all went the same direction.  My character was also invisible when in 3rd person.

I've included the log from the last login with it.  It's a little messy because I was testing a bunch of mods, so let me know if there's something else I can do to help.
[dynsurroundings_freeze_in_place.log](https://github.com/OreCruncher/DynamicSurroundings/files/6120413/dynsurroundings_freeze_in_place.log)

edit: I did try both the jar on Curseforge and the jar listed in this thread.  Same results.
edit2 (sorry, first time posting on github, got nervous!): I was able to release myself from the "freeze" by either using /mvtp (multiverse teleport) or /kill and respawning myself, but would be frozen again whenever I disconnected and reconnected.  Normal /tp did not fix the issue, however.

**Comment by OreCruncher** [comment]
Argh!  Yet another Paper/Spigot/Bukkit/Cheetah thing!  This is going to be fun. :\

**Comment by Jump-Suit** [comment]
> 
> 
> Try out this JAR: https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.4.1

I had this issue, where in a realm I couldn't move on spawning in, this jar fixed the issue! Good dev support!!! A++

**Comment by Tsunamori74** [comment]
I'm having this same exact issue, but with my own dedicated server. The strangest part is that it only happens to me, while my friends can log in and move around without any issues. I solved it by rolling back one version of DS but it's really strange.

**Comment by OreCruncher** [comment]
Try this updated JAR and let me know if there is a difference. I changed how the handshake works when connecting to a server. https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/1.16.4-4.0.4.1

**Comment by HereToSaySomething** [comment]
The issue has been fixed for me. Thank you.

**Comment by OreCruncher** [comment]
I am going to leave this open until I push the new bits to CurseForge.  Thanks for updating me on this - I appreciate it.
