### ISSUE TITLE
[1.16.4] Footsteps not affected by any of the sound sliders

### ISSUE THREAD

**Issue by Talyda** [OreCruncher/DynamicSurroundings#706]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.3.11.jar

**Forge Version:**

35.1.37

**Link to client log:**

No crash

**Link to crash log:**

No crash

**Description:**

Playing the Mineshafts and Monsters modpack.

There's a footstep sound, it is VERY loud. I tried lowering the slider for footsteps to 0 and it had no effect.

I changed all the sliders in minecraft (other than master volume level) to 0 and the footstep sound is still not affected. The only way to lower it at all is to lower the master volume slider.

I also disabled dynamic surroundings, just to be sure that the mod itself was controlling the sound, and with it disabled the footstep sound is gone, so it's definitely dynamic surroundings that is handling it =)

Happy to provide any other info, or test anything!

**Comment by OreCruncher** [comment]
Update to the latest version 4.0.4.1 so I have a recent baseline to work with.

**Comment by Talyda** [comment]
Sorry, can't believe I did that =P

Anyway, did update, still the same - using ctrl+v (I think that was the one) moved footsteps down to 0 and could still hear them, then the main minecraft sliders all down to 0 and can still hear them. Adjusting the master volume is still the only way to change that sound =)

**Comment by OreCruncher** [comment]
It appears there is another mod interfering.  I am not seeing calls coming into to get a clamped volume for non-streaming sounds.  (The clamped volume calculation evaluates the actual effective volume for a sound when it is played, factoring in various config sliders and what not.)  The net effect is that the volume scaling for footsteps is not being applied.  DS uses a Mixin to hook this particular method call in the sound engine so that it can apply its volume effects.  The fun part now is to figure out what mod is doing it.

EDIT: Found it.  It's EnhancedVisuals.  It overrides the clamping routine so it can apply muting.  As a result my mod never gets  chance.  There are no options in EnhancedVisuals to control so to fix you will need to disable that mod.

**Comment by Talyda** [comment]
Thank you! Will do so! =)

Do you want me to make an issue with them?

*edits* Never mind, I saw that you did =)

**Comment by OreCruncher** [comment]
@Talyda CreativeMD made a fix on his side for compatibility.  I am going to close this as resolved.  If you have further issues along this line feel free to re-open.

**Comment by Talyda** [comment]
Thanks for letting me know!
