### ISSUE TITLE
[SUGGESTION FOR MUSIC] A suggestion based off of past experience, and then some

### ISSUE THREAD

**Issue by Sunconure11** [OreCruncher/DynamicSurroundings#88]
While it does cost a few bucks, music by Nox Arcana might be fitting for some of the things, and it is relatively easy to get the permissions from them to use their music, at least, the last time I asked about it, for a dead project. Just tell them the exact songs you want to use. http://noxarcana.com/

Some examples of their music:

https://www.youtube.com/watch?v=nGLGxjXYuKI

https://www.youtube.com/watch?v=4HfoOy8K2CI

https://www.youtube.com/watch?v=avCcKRZD_Gs

Alternatively, you could search around soundcloud, bandcamp, youtube, and what not, and ask smaller music producers for permissions. Just make sure to credit them in the code. For bosses, I'd advise looking at producers of "Epic Music".

Some examples of this genre:

https://www.youtube.com/watch?v=90PRvlhOLSk

https://www.youtube.com/watch?v=KE47kkwLH2w (good luck with securing permissions from Globus lol)

https://www.youtube.com/watch?v=d2hRTLdvdnk (TSFH would also be pretty hard, as they do not accept permission requests from non-commercial individuals anymore.)

https://www.youtube.com/watch?v=3aYiiGd3PZc

https://www.youtube.com/watch?v=ySXsFk3v-_E

https://www.youtube.com/watch?v=oUlclgxgNAo

https://www.youtube.com/watch?v=2UeA9Nus9Eg

**Comment by OreCruncher** [comment]
Speaking of, I was looking at replacing the Music Ticker in Minecraft.  This is the guy that periodically plays the background music based on time of day, dimension, etc. within Minecraft.  My main reason for doing this is so I can automute that sound when fight music is playing, but I started thinking about some other possibilities:
+ Rule based similar to other sounds.  For example a rule could be created to play one type of background music if in a specific dimension than another.
+ Instead of allowing a single sound per MusicType use a WeightTable and randomly select a possible sound.  This will allow for some musical variation when more than one sound matches a rule.
+ Would be configurable via external config files like every thing else.
+ Display some credit information as if a record in a juke box was playing.  You can see this with the Dragon and Wither fight songs.

**Comment by OreCruncher** [comment]
Took a listen and some of those sound pretty good.  What I been thinking of as of late is what a Minecrafty like battle music sound like.

**Comment by EchenCraft** [comment]
I have to second this suggestion. For the modpack im working on I was going to be implementing music from Nox Arcana myself and hadn't tested it yet but was planning on trying to get actualmusic or ambience to play nice with Dynamic Surroundings in order to get this into the pack. If you could add something like this into Dynamic Surroundings It would not only make my life easier but reduce some overhead as well. 

I like the idea of combat music I just dont really like the choice you made for normal combat.... not that its bad, it just doesnt fit well with my pack......... however I give you props on its implementation as it works great and I love the way it fades in and out. 

If you plan on adding more music like mentioned above Ill further that suggestion and say It would be awsome to be able to pick (through config) from a selection of tracks for things lke combat or maybe something simpler like picking themes.... some may like Nox Arcana style music while others may want something whimsical

**Comment by OreCruncher** [comment]
Fokson and I did some work this past week to get ActualMusic and DS playing together.  You may want to check out the latest BETA that was posted.

As for music you could replace the DS music with your own.  It just needs a bit of configuration on the DS side to tell it to use the files in your resource pack rather than the built-in ones.

**Comment by EchenCraft** [comment]
That would work for some friends but would require editing files in the jar if I'm not mistaken... I plan on uploading this pack to curseforge so I wouldn't dream of anything to take away from your download count and probably wouldn't get past curse anyway. What I was hoping to do was replace some of your music.. like the combat music ... with Nox style sounds using actual music to override DS but I haven't even began to dale in that and wasnot even sure If I'd be able to pull that off... I'll defiantly be checking out that beta though as soon as I get what I have  stable.

**Comment by OreCruncher** [comment]
You don't have to edit a JAR.  You can make an external resource pack that has the songs you want, and put in a configuration file in that resource pack that DS will recognize. :)  (Note that the resource pack could contain other sounds and configurations as well.)  All a user would have to do is drop the pack into the resource pack folder and add it via the Minecraft config.

**Comment by EchenCraft** [comment]
I misunderstood, Yes I was going to be doing exactly that earlier on for custom main menu music as it just refused to load from resourceloader and thought I may be able to override some other stuff too like from DS. completely forgot about that but remember I put that on hold for a bit because I wasnt sure what the proper path should be and then started looking at the soundpack mods. Im still kinda new to the modding thing, I used to build spigot servers but got bored with it and then discovered mods and have wondered why I never used them before. An example would be awesome and save me time figuring out how to path the files right.. what confuses me about mods is that, minecraft starts with net.mineccraft but with mods its different.

I assume the files should start with assets.modname.sounds and then follow the path laid out in the jar.....or maybe asstes.modname and then path in the jar?

**Comment by OreCruncher** [comment]
That's pretty close.  For this I would also recommend your own sounds.json as well so you can keep them in your own resource domain and supply some config data.  I will work on pulling together an example pack to post on github.

**Comment by darthvader45** [comment]
I'd love to see that example pack.  Maybe some examples of battle music too?

**Comment by OreCruncher** [comment]
Revisiting this issue.  With the latest BETA versions of DS (3.5.4.x) Battle Music assets have been moved into an external resource pack. The implication here is that a pack containing the music you want can be created and when activated DS will pick it up and use it.  Details can be found [here](https://dynamicsurroundings.readthedocs.io/en/master/features/battlemusic.html).  The resource pack can also be used to supply other biome sounds and configuration as well.

Since there is resource pack support (and the battle music has been moved to a resourcepack) I am going to close out the issue.  The solution would be to create a resource pack with your own music.

**Comment by darthvader45** [comment]
Awesome, thanks OreCruncher.  Now I can have just the song I want playing
when fighting normal mobs or a boss like the Ender Dragon.
